# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Fln_cpp_fast <- function(x) {
    .Call(`_nSGMM_Fln_cpp_fast`, x)
}

logpotential_fast_cpp <- function(transfers, logaltruism, income) {
    .Call(`_nSGMM_logpotential_fast_cpp`, transfers, logaltruism, income)
}

gr_logpotential_fast_cpp <- function(transfers, logaltruism, income) {
    .Call(`_nSGMM_gr_logpotential_fast_cpp`, transfers, logaltruism, income)
}

gr_logpotential_fake_cpp <- function(transfers, logaltruism, income) {
    .Call(`_nSGMM_gr_logpotential_fake_cpp`, transfers, logaltruism, income)
}

gr_logpotential_old_cpp <- function(transfers, logaltruism, income) {
    .Call(`_nSGMM_gr_logpotential_old_cpp`, transfers, logaltruism, income)
}

utlity_cppvec <- function(consumption, altruism) {
    .Call(`_nSGMM_utlity_cppvec`, consumption, altruism)
}

mynegutility_cpp <- function(mytransfers, i, transfers, altruism, income) {
    .Call(`_nSGMM_mynegutility_cpp`, mytransfers, i, transfers, altruism, income)
}

mynegutility_cpp_consumption <- function(mytransfers, i, transfers, altruism, consumption) {
    .Call(`_nSGMM_mynegutility_cpp_consumption`, mytransfers, i, transfers, altruism, consumption)
}

get_BBP_BR_analytically_cpp_inline <- function(i, transfers, income, altruism, capacities) {
    .Call(`_nSGMM_get_BBP_BR_analytically_cpp_inline`, i, transfers, income, altruism, capacities)
}

BBP_in_equilibrium_YaT_cpp <- function(transfers, income, altruism, capacities, tolerance) {
    .Call(`_nSGMM_BBP_in_equilibrium_YaT_cpp`, transfers, income, altruism, capacities, tolerance)
}

meannanrm <- function(x, dim) {
    .Call(`_nSGMM_meannanrm`, x, dim)
}

consumption_weights_cpp <- function(alphas, transfers, t_conmat) {
    .Call(`_nSGMM_consumption_weights_cpp`, alphas, transfers, t_conmat)
}

BBP_c_from_atY_cpp <- function(alphas, transferstructure, incomes, t_components_matrix, t_components_csize, t_conmat) {
    .Call(`_nSGMM_BBP_c_from_atY_cpp`, alphas, transferstructure, incomes, t_components_matrix, t_components_csize, t_conmat)
}

BBP_T_from_tYc_cpp <- function(transferstructure, incomes, consumptions, Tr, depth = 0L) {
    .Call(`_nSGMM_BBP_T_from_tYc_cpp`, transferstructure, incomes, consumptions, Tr, depth)
}

BBP_T_from_atY_plain_cpp <- function(alphas, transferstructure, incomes) {
    .Call(`_nSGMM_BBP_T_from_atY_plain_cpp`, alphas, transferstructure, incomes)
}

equilibrate_cpp_fast8_debug <- function(altruism, income, capacity, transfers, verbose, r, NE, maxrounds = 500L) {
    .Call(`_nSGMM_equilibrate_cpp_fast8_debug`, altruism, income, capacity, transfers, verbose, r, NE, maxrounds)
}

equilibrate_cpp_fast8_smarter <- function(altruism, income, capacity, startnet, maxrounds = 500L) {
    .Call(`_nSGMM_equilibrate_cpp_fast8_smarter`, altruism, income, capacity, startnet, maxrounds)
}

berlin_mwe <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_berlin_mwe`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

berlin_mwe2 <- function(n) {
    .Call(`_nSGMM_berlin_mwe2`, n)
}

recip_cpp <- function(adj, radj) {
    .Call(`_nSGMM_recip_cpp`, adj, radj)
}

component_counts <- function(transferstructure) {
    .Call(`_nSGMM_component_counts`, transferstructure)
}

Ccomponents <- function(transferstructure, t_components_csize, t_components_membership, t_components_matrix, t_conmat) {
    .Call(`_nSGMM_Ccomponents`, transferstructure, t_components_csize, t_components_membership, t_components_matrix, t_conmat)
}

forestness_cpp <- function(adj) {
    .Call(`_nSGMM_forestness_cpp`, adj)
}

zeroOneBFS <- function(m, src) {
    .Call(`_nSGMM_zeroOneBFS`, m, src)
}

BFS_dist_all <- function(graph) {
    .Call(`_nSGMM_BFS_dist_all`, graph)
}

dijkstra <- function(graph, src) {
    .Call(`_nSGMM_dijkstra`, graph, src)
}

dijkstra_all <- function(graph) {
    .Call(`_nSGMM_dijkstra_all`, graph)
}

dskewness <- function(adj) {
    .Call(`_nSGMM_dskewness`, adj)
}

degreesd <- function(adj) {
    .Call(`_nSGMM_degreesd`, adj)
}

compute_moments_cpp <- function(btransfers, kinship, distance, income) {
    .Call(`_nSGMM_compute_moments_cpp`, btransfers, kinship, distance, income)
}

random_normal_seed <- function(n, mean, sd, seed) {
    .Call(`_nSGMM_random_normal_seed`, n, mean, sd, seed)
}

symmetrix_normal_error_matrix <- function(n, mean, sd, seed) {
    .Call(`_nSGMM_symmetrix_normal_error_matrix`, n, mean, sd, seed)
}

normal_error_matrix <- function(n, mean, sd, seed) {
    .Call(`_nSGMM_normal_error_matrix`, n, mean, sd, seed)
}

seedfromindex <- function(index) {
    .Call(`_nSGMM_seedfromindex`, index)
}

simulate_BBP_cpp <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp_parallel <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp_parallel`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp73 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp73`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp1 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp1`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp2 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp2`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp3 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp3`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp4 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp4`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp5 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp5`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

simulate_BBP_cpp6 <- function(n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds) {
    .Call(`_nSGMM_simulate_BBP_cpp6`, n, delta0, delta1, sigma, distance, kinship, capacity, income, reps, seed, rounds)
}

